SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[spModel_GetAll]
  @skip INT,
  @take INT,
  @total INT OUTPUT
AS
BEGIN
  SET NOCOUNT ON;

  SELECT id, modelName
  FROM dbo.Model
  ORDER BY Id
    OFFSET @skip ROWS
    FETCH NEXT @take ROWS ONLY
  FOR JSON PATH;

  SELECT @total = COUNT(id)
  FROM dbo.Model;
END
GO