SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[spTFLiteRecord_GetById]
  @id int
AS
BEGIN
  SET NOCOUNT ON;

  SELECT zipContent
  FROM dbo.TFLiteRecord
  WHERE id = @id;
END
GO