version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/services/record/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/services/record/api"
    schedule:
      interval: "weekly"