version: "3.9"

services:
  mariadb:
    build:
      context: ./mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "${ROOT_PASSWORD}"
    networks:
      - appnet

  record-api:
    build:
      context: ./record-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings:RecordDb: "Server=mariadb,3306;Database=RecordDb;User Id=root;Pwd=${ROOT_PASSWORD};"
    ports:
      - 8000:80
    networks:
      - appnet

  node-socket:
    build:
      context: ./node-socket
    networks:
      - appnet

  vue-app:
    build: 
      context: ./vue-app
      args:
        mode: compose
    ports: 
      - 8100:80
    networks:
      - appnet

  coral-app:
    build: 
      context: ./coral-app
    networks:
      - appnet
  
  proxy:
    build:
      context: ./proxy
    ports:
      - 80:80
    depends_on:
      - record-api
      - node-socket
    networks:
      - appnet

networks:
  appnet:
    driver: bridge