version: "3.9"

services:
  mariadb:
    image: jensdll/coral-ml:mariadb_latest
    environment:
      MARIADB_ROOT_PASSWORD: Pwd12345!
    networks:
      - appnet

  record-api:
    image: jensdll/coral-ml:record-api_latest
    environment:
      ConnectionStrings:RecordDb: "Server=mariadb,3306;Database=RecordDb;User Id=root;Pwd=Pwd12345!;"
    depends_on:
      - mariadb
    networks:
      - appnet

  node-api:
    image: jensdll/coral-ml:node-api_latest
    networks:
      - appnet

  node-video:
    image: jensdll/coral-ml:node-video_latest
    networks:
      - appnet

  vue-app:
    image: jensdll/coral-ml:vue-app_latest
    ports: 
      - 8080:80
    networks:
      - appnet

  coral-app:
    image: jensdll/coral-ml:coral-app_latest
    networks:
      - appnet
  
  proxy:
    image: jensdll/coral-ml:proxy_latest
    ports:
      - 80:80
    depends_on:
      - record-api
      - node-api
      - node-video
    networks:
      - appnet

networks:
  appnet:
    driver: bridge