version: "3.9"

services:
  mariadb:
    build:
      context: ./mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "${ROOT_PASSWORD}"
    ports:
      - ${DB_PORT}:3306
    networks:
      - appnet

  recordapi:
    build:
      context: ./record-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings:RecordDb: "Server=mariadb,${DB_PORT};Database=RecordDb;User Id=root;Pwd=${ROOT_PASSWORD};"
    ports:
      - 8000:80
    depends_on:
      - mariadb
    networks:
      - appnet

  nodesocket:
    build:
      context: ./node-socket
    networks:
      - app-net

  vueapp:
    build: 
      context: ./vue
    ports: 
      - 8100:80
    networks:
      - appnet

  coralapp:
    build: 
      context: ./coral-app
    networks:
      - appnet

networks:
  appnet:
    driver: bridge