# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import stream_pb2 as stream__pb2


class StreamerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCamProps = channel.unary_unary(
                '/Streamer/GetCamProps',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stream__pb2.CamProps.FromString,
                )
        self.ReadFrames = channel.unary_stream(
                '/Streamer/ReadFrames',
                request_serializer=stream__pb2.ReadFramesRequest.SerializeToString,
                response_deserializer=stream__pb2.Frame.FromString,
                )


class StreamerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCamProps(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCamProps': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCamProps,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stream__pb2.CamProps.SerializeToString,
            ),
            'ReadFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadFrames,
                    request_deserializer=stream__pb2.ReadFramesRequest.FromString,
                    response_serializer=stream__pb2.Frame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Streamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Streamer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCamProps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Streamer/GetCamProps',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stream__pb2.CamProps.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Streamer/ReadFrames',
            stream__pb2.ReadFramesRequest.SerializeToString,
            stream__pb2.Frame.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
