# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='stream.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cstream.proto\x1a\x1bgoogle/protobuf/empty.proto\"5\n\x08\x43\x61mProps\x12\x13\n\x0b\x66rame_width\x18\x01 \x01(\x05\x12\x14\n\x0c\x66rame_height\x18\x02 \x01(\x05\"D\n\x11ReadFramesRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\r\n\x05\x64type\x18\x02 \x01(\t\x12\r\n\x05width\x18\x03 \x01(\x05\"\x16\n\x05\x46rame\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x32l\n\x08Streamer\x12\x32\n\x0bGetCamProps\x12\x16.google.protobuf.Empty\x1a\t.CamProps\"\x00\x12,\n\nReadFrames\x12\x12.ReadFramesRequest\x1a\x06.Frame\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_CAMPROPS = _descriptor.Descriptor(
  name='CamProps',
  full_name='CamProps',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_width', full_name='CamProps.frame_width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_height', full_name='CamProps.frame_height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=98,
)


_READFRAMESREQUEST = _descriptor.Descriptor(
  name='ReadFramesRequest',
  full_name='ReadFramesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='ReadFramesRequest.client_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='ReadFramesRequest.dtype', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='ReadFramesRequest.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=168,
)


_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='Frame.frame', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=192,
)

DESCRIPTOR.message_types_by_name['CamProps'] = _CAMPROPS
DESCRIPTOR.message_types_by_name['ReadFramesRequest'] = _READFRAMESREQUEST
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CamProps = _reflection.GeneratedProtocolMessageType('CamProps', (_message.Message,), {
  'DESCRIPTOR' : _CAMPROPS,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:CamProps)
  })
_sym_db.RegisterMessage(CamProps)

ReadFramesRequest = _reflection.GeneratedProtocolMessageType('ReadFramesRequest', (_message.Message,), {
  'DESCRIPTOR' : _READFRAMESREQUEST,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:ReadFramesRequest)
  })
_sym_db.RegisterMessage(ReadFramesRequest)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), {
  'DESCRIPTOR' : _FRAME,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:Frame)
  })
_sym_db.RegisterMessage(Frame)



_STREAMER = _descriptor.ServiceDescriptor(
  name='Streamer',
  full_name='Streamer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=194,
  serialized_end=302,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCamProps',
    full_name='Streamer.GetCamProps',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_CAMPROPS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReadFrames',
    full_name='Streamer.ReadFrames',
    index=1,
    containing_service=None,
    input_type=_READFRAMESREQUEST,
    output_type=_FRAME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAMER)

DESCRIPTOR.services_by_name['Streamer'] = _STREAMER

# @@protoc_insertion_point(module_scope)
