const BASE_ADDRESS = `tcp://${process.env.CORAL_HOST}:`

export const URI = {
  MODEL_MANAGER: BASE_ADDRESS + process.env.CORAL_PORT_MODEL_MANAGER,

  IMAGE_CLASSIFICATION:
    BASE_ADDRESS + process.env.CORAL_PORT_IMAGE_CLASSIFICATION,
  IMAGE_UPDATE_SETTINGS: BASE_ADDRESS + process.env.CORAL_PORT_IMAGE_SETTINGS,

  VIDEO_UPDATE_SETTINGS: BASE_ADDRESS + process.env.CORAL_PORT_VIDEO_SETTINGS
}
