name: Docker Hub Publish CI

on:
  release:
    types:
      - "published"

jobs:
  publish-images:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set Environment Variables
      run: |
        echo "TAG=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
    - name: Build and Push Images
      run: |
        docker buildx bake -f docker-bake.hcl --print
